title: "Andrew Pasco"
description: "Personal website"
theme: jekyll-theme-slate

collections:
  blog:
    output: true

nav_pages:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Projects"
    url: "/projects"
  - title: "Resume"
    url: "/resume"
  - title: "Links"
    url: "/links"
  - title: "Contact"
    url: "/contact"
